travis:
  secure:
    BINSTAR_TOKEN: DXSrcIXVn1Moi6ws7RZjXd7npQsSOmLHdRVP2pNjjeTb1nkNas/ftDOKR3U9/iBc2/tAMWsVolTGwlB1XCiHbz2ftNmUr6y5g6yUPR+zI8+OAFTdOwNvJreCM5kZhucnimdf8sJvMjT3Ftzyofss3Us9mS2vNnzU8NQJuKaznqnG8+DRRcNH6xNIhqCGTBk6jqlWZNKP09+WNAcU5s3w1UYBC4UqdD7DbX57/Vh0f+zqGMuTLdUpYIhICItMydbtnvQDhqp2L0SMlwfZdA+nVilr/6fjSik8KMgjj8ss9sopXJdgm0p9j8r/bqyKZOfoRDhkhARN4lnXKi61VZ2YkvbJ/tEbFEUXE4oU3L3YN+p3ZBKgS31Tzoq8U0rMhpLHSuS0vIvx7VRY6jfJFZgDfaBVC6iw6+BoShr4R7TET+n1nn9z0DyJYBhot2p5NsXvbKdbsmOJRsh3Wtvi5JUmr5MJPIg4rQJEpirvIU2To1fD8qaiXNgAtaY8odXiPYVd05oIL06gcJr4xu0YSGlEQdN1luAFJTJkQ1sOJh4OnUnfwRc0rgh+deH8etPhDu8rKMJd9vvsG93+K8IOBPwCgoac35ylJFe93tyzuXcCMtC1+CkytAHS39kpmyiEDaSlcKnZlxYAGMpyN67wPofL6Jv0Y3DRQc82VNlUFI27MBw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
